#!/usr/bin/env node

'use strict'

const fs = require('fs')
const path = require('path')

// This script updates the index files list.js and list.txt in the bin directory,
// as well as the soljson-latest.js files.

fs.readdir(path.join(__dirname, '/bin'), function (err, files) {
  if (err) {
    throw err
  }

  const parsedList = files
    .map(function (file) { return file.match(/^soljson-v([0-9.]*)(-([^+]*))?(\+(.*))?.js$/) })
    .filter(function (version) { return version })
    .map(function (pars) { return { path: pars[0], version: pars[1], prerelease: pars[3], build: pars[5] } })

  // descending list
  const releases = parsedList
    .slice().reverse()
    .reduce(function (prev, next) {
      if (next.prerelease === undefined) {
        prev[next.version] = next.path
      }
      return prev
    }, {})

  // descending list
  const buildNames = parsedList
    .slice().reverse()
    .map(function (ver) { return ver.path })

  // latest build
  const latestBuildFile = buildNames[0]

  // Write bin/list.txt
  // A descending list of file names.
  fs.writeFile(path.join(__dirname, '/bin/list.txt'), buildNames.join('\n'), function (err) {
    if (err) {
      throw err
    }
    console.log('Updated bin/list.txt')
  })

  // Write bin/list.json
  // Ascending list of builds and descending map of releases.
  fs.writeFile(path.join(__dirname, '/bin/list.json'), JSON.stringify({ builds: parsedList, releases: releases }, null, 2), function (err) {
    if (err) {
      throw err
    }
    console.log('Updated bin/list.json')
  })

  // Write bin/list.js
  // Descending list of build filenames and descending map of releases.
  fs.writeFile(path.join(__dirname, '/bin/list.js'), generateLegacyListJS(buildNames, releases), function (err) {
    if (err) {
      throw err
    }
    console.log('Updated bin/list.js')
  })

  // Read latest build file
  fs.readFile(path.join(__dirname, '/bin/', latestBuildFile), function (err, data) {
    if (err) {
      throw err
    }

    // Copy to bin/soljson-latest.js
    fs.writeFile(path.join(__dirname, '/bin/soljson-latest.js'), data, function (err) {
      if (err) {
        throw err
      }
      console.log('Updated bin/soljson-latest.js')
    })

    // Copy to soljson.js
    fs.writeFile(path.join(__dirname, '/soljson.js'), data, function (err) {
      if (err) {
        throw err
      }
      console.log('Updated soljson.js')
    })
  })
})

function generateLegacyListJS (builds, releases) {
  return `
var soljsonSources = ${JSON.stringify(builds, null, 2)};
var soljsonReleases = ${JSON.stringify(releases, null, 2)};

if (typeof(module) !== 'undefined')
  module.exports = {
    'allVersions': soljsonSources,
    'releases': soljsonReleases
  };
`
}
